apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: scan
description: "Scan using multiple plugins"

outputs:
  #Code Scan related Outputs
  account_credentials:
    value: ${{ steps.plan.outputs.account_credentials}}
    description: "Account credentials"
  github-inventory:
    value: ${{ steps.plan.outputs.github-inventory}}
    description: "Github inventory"
  github-decorator:
    value: ${{ steps.plan.outputs.github-decorator}}
    description: "Github decorator"
  bitbucket-inventory:
    value: ${{ steps.plan.outputs.bitbucket-inventory}}
    description: "Bitbucket inventory"
  bitbucket-decorator:
    value: ${{ steps.plan.outputs.bitbucket-decorator}}
    description: "Bitbucket decorator"
  gerrit-inventory:
    value: ${{ steps.plan.outputs.gerrit-inventory}}
    description: "Gerrit inventory"
  gerrit-decorator:
    value: ${{ steps.plan.outputs.gerrit-decorator}}
    description: "Gerrit decorator"
  gitlab-inventory:
    value: ${{ steps.plan.outputs.gitlab-inventory}}
    description: "Gitlab inventory"
  gitlab-decorator:
    value: ${{ steps.plan.outputs.gitlab-decorator}}
    description: "Gitlab decorator"
  scc:
    value: ${{ steps.plan.outputs.scc}}
    description: "SCC Scanner"
  gosec:
    value: ${{ steps.plan.outputs.gosec}}
    description: "Gosec"
  njsscan:
    value: ${{ steps.plan.outputs.njsscan}}
    description: "NJS"
  gitleaks:
    value: ${{ steps.plan.outputs.gitleaks}}
    description: "Gitleaks"
  sonar-props:
    value: ${{ steps.plan.outputs.sonar-props}}
    description: "SonarQube"
  sonar:
    value: ${{ steps.plan.outputs.sonar}}
    description: "SonarQube Scanner"
  checkov:
    value: ${{ steps.plan.outputs.checkov}}
    description: "Checkov"
  blackduck-props:
    value: ${{ steps.plan.outputs.blackduck-props}}
    description: "BlackDuck"
  blackduck:
    value: ${{ steps.plan.outputs.blackduck}}
    description: "BlackDuck Scanner"
  coverity-props:
    value: ${{ steps.plan.outputs.coverity-props}}
    description: "Coverity"
  coverity:
    value: ${{ steps.plan.outputs.coverity}}
    description: "Coverity Polaris"
  perforce-klocwork-sast-props:
    value: ${{ steps.plan.outputs.perforce-klocwork-sast-props}}
    description: "Perforce Klocwork"
  perforce-klocwork-sast:
    value: ${{ steps.plan.outputs.perforce-klocwork-sast}}
    description: "Perforce Klocwork Scanner"
  snykcode-props:
    value: ${{ steps.plan.outputs.snykcode-props}}
    description: "Snyk SAST"
  snykcode:
    value: ${{ steps.plan.outputs.snykcode}}
    description: "Snyk SAST Scanner"
  snyk-iac-props:
    value: ${{ steps.plan.outputs.snyk-iac-props}}
    description: "Snyk IaC"
  snyk-iac:
    value: ${{ steps.plan.outputs.snyk-iac}}
    description: "Snyk IaC Scanner"
  snyksca-props:
    value: ${{ steps.plan.outputs.snyksca-props}}
    description: "Snyk SCA"
  snyksca:
    value: ${{ steps.plan.outputs.snyksca}}
    description: "Snyk SCA Scanner"
  
  #Binary Scan related Outputs
  wf_artifact_token:
    value: ${{ steps.plan.outputs.wf_artifact_token }}
    description: "Workflow artifact token"
  wf_artifact_component_id:
    value: ${{ steps.plan.outputs.wf_artifact_component_id }}
    description: "Workflow artifact component id"
  wfartifact-inventory:
    value: ${{ steps.plan.outputs.wfartifact-inventory}}
    description: "Workflow artifact inventory"
  wfartifact-decorator:
    value: ${{ steps.plan.outputs.wfartifact-decorator}}
    description: "Workflow artifact decorator"
  ecr-inventory:
    value: ${{ steps.plan.outputs.ecr-inventory}}
    description: "ECR inventory"
  ecr-metadata:
    value: ${{ steps.plan.outputs.ecr-metadata}}
    description: "ECR metadata"
  ecr_role_arn:
    value: ${{ steps.plan.outputs.ecr_role_arn}}
    description: "ECR Role ARN"
  ecr_region_name:
    value: ${{ steps.plan.outputs.ecr_region_name}}
    description: "ECR Region Name"
  jfrog-inventory:
    value: ${{ steps.plan.outputs.jfrog-inventory}}
    description: "JFrog Artifactory Inventory"
  jfrog-metadata:
    value: ${{ steps.plan.outputs.jfrog-metadata}}
    description: "JFrog Artifactory Metadata"
  trivy:
    value: ${{ steps.plan.outputs.trivy}}
    description: "Trivy"
  findsecbugs:
    value: ${{ steps.plan.outputs.findsecbugs}}
    description: "FindSecBugs"
  syft:
    value: ${{ steps.plan.outputs.syft}}
    description: "Syft SBOM"
  grype:
    value: ${{ steps.plan.outputs.grype}}
    description: "Grype"

runs:
  using: composite
  steps:
    - name: Initiate execution plan
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:805ec930ea41c76375697b921a6a75601afaed3a
      id: plan
      with:
        entrypoint: assets-plugin-chain-utils
        args: configure
      env:
        INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        INPUT_RUN_ID: ${{ cloudbees.run_id }}
        INPUT_INIT_OUTPUTS: 'wf_artifact_component_id,wf_artifact_token,account_credentials,github-inventory,github-decorator,scc,bitbucket-inventory,bitbucket-decorator,gerrit-inventory,gerrit-decorator,gosec,njsscan,gitleaks,checkov,wfartifact-inventory,wfartifact-decorator,trivy,findsecbugs,syft,grype,sonar,sonar-props,blackduck,blackduck-props,coverity,coverity-props,perforce-klocwork-sast,perforce-klocwork-sast-props,snykcode,snykcode-props,snyk-iac,snyk-iac-props,snyksca,snyksca-props,ecr_role_arn,ecr_region_name,ecr-inventory,ecr-metadata,gitlab-inventory,gitlab-decorator,jfrog-inventory,jfrog-metadata'
        INPUT_TIMEOUT: "120" # 2 minutes
