apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: scan
description: "End scan chain"

runs:
  using: composite
  steps:
    - name: Complete execution plan
      uses: docker://public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:d621d66df83be71f6b4b1d1ac7ac9e0de6f6fc7d
      id: process-outputs
      with:
        entrypoint: assets-plugin-chain-utils
        args: process-outputs
      env:
        INPUT_CLOUDBEES_API_TOKEN: ${{ cloudbees.api.token }}
        INPUT_CLOUDBEES_API_URL: ${{ cloudbees.api.url }}
        INPUT_RUN_ID: ${{ cloudbees.run_id }}
